Repository ucsb-cs156-f23/proj-organic-f23-6pm-2, pull requests merged in 2023-11, with the labels that each got.

#14 fixed spacing issue in class
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 5, Merge Candidate

#17 Backend Endpoint Interceptors and Updater
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorAppConfig.java
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/MockCurrentUserServiceImpl.java
Labels: 10

#32 Priority F1: fixtures, form component, and table component for Courses
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/utils/coursesUtils.js
  frontend/src/stories/components/Courses/CoursesForm.stories.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/utils/coursesUtils.test.js
Labels: Merge Candidate, 10

#47 Deployed prod on dokku
  README.md
Labels: 5, Merge Candidate

#48 QA Dokku Deployment
  README.md
Labels: 0

#29 F1-Add Toggle Admin and Instructor Buttons to frontend
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/pages/AdminUsersPage.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/main/utils/users.js
  frontend/src/stories/components/Users/UsersTable.stories.js
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: 10

#31 [User] F1 UserTable Story and Tests
  frontend/.storybook/main.js
  frontend/src/stories/components/Users/UsersTable.stories.js
Labels: 5, Merge Candidate

#49 Web metadata change
  frontend/public/index.html
Labels: 5, Merge Candidate

#51 [Course] F1.5: Navbar link to courses + placeholders for courses pages
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Courses/CoursesCreatePage.js
  frontend/src/main/pages/Courses/CoursesEditPage.js
  frontend/src/main/pages/Courses/CoursesIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
  frontend/src/tests/pages/Courses/CoursesEditPage.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
Labels: Merge Candidate, 10

#52 [Course] B2: Backend PUT/DELETE operations, Course Controller
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/repositories/StaffRepository.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: Merge Candidate, 10

#54 [Course] B1: Backend POST / GET operations for Course
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/JobsControllerTests.java
Labels: Merge Candidate, 10

#64 [School] B1+B2: Backend Issue: entity/repository for schools and GET all, GET by id, POST operations for Schools
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolsController.java
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/main/resources/db/migration/changes/0007_CreateSchoolsTable.json
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolsControllerTests.java
Labels: Merge Candidate, 10

#66 Fix courses api endpoints by fixing "end" postgres keyword conflict
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/entities/Course.java
  src/main/resources/db/migration/changes/0005_CreateCourseTable.json
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/StudentsControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/UserInfoControllerTests.java
Labels: PRIORITY, Merge Candidate, 10
